version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5555:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - pg-net

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net: