repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--max-line-length=88", "--ignore=E203, W503"]

  - repo: local
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        args: ['--ignore=D100,D107,D407,D406,D212,D203']

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--follow-imports=silent",
               "--disallow-untyped-defs",
               "--ignore-missing-imports",
               "--no-namespace-packages"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
