"""add santa col to participant

Revision ID: bb699de21a6a
Revises: a40bae70b4c0
Create Date: 2024-11-25 23:35:40.077884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb699de21a6a'
down_revision: Union[str, None] = 'a40bae70b4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('santa_to', sa.UUID(), nullable=True))
    op.add_column('participant', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'participant', 'user', ['santa_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'created_at')
    op.drop_column('participant', 'santa_to')
    # ### end Alembic commands ###
